Repository Jiggy9/JCT, pull requests merged in 2024-10, with the labels that each got.

#33 Profile section save button not working after putting data #16
  android/app/build.gradle
  android/app/google-services.json
  firebase.json
  lib/firebase_options.dart
  lib/screens/feedback/feedback_providers/feedback_provider.dart
  lib/screens/feedback/feedback_screen/feedback_screen.dart
  lib/screens/user/usefull/profile_page.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#42 [feat:🦄]: added Bottom Navigation
  lib/screens/bottom_navigation/provider/bottom_nav_provider.dart
  lib/screens/bottom_navigation/screen/bottom_navigation.dart
  lib/screens/user/usefull/important_screen.dart
  lib/widgets/home_page_widget.dart
  pubspec.lock
Labels: gssoc-ext, hectoberfest-accepted

#44 [BUG] IOS Build failing resolved.
  ios/Flutter/AppFrameworkInfo.plist
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/AppDelegate.swift
  lib/screens/bottom_navigation/provider/bottom_nav_provider.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#49 added: Firebase_Setup_manual
  FIREBASE_SETUP.md
Labels: gssoc-ext, hacktoberfest-accepted, level3

#74 UI: redesign the Auth screens and fixed Scope issue
  lib/main.dart
  lib/screens/user/login/signin_screen.dart
  lib/screens/user/login/signup_screen.dart
  lib/screens/welcome_screen.dart
Labels: gssoc-ext, hacktoberfest-accepted, level3
